name: Generate Go Proto Files

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout generated repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Set up protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "25.3"

      - name: Install protobuf plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.2
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Clean previous generated files
        run: |
          rm -rf order payment proto-src

      - name: Clone proto repository
        run: |
          git clone https://github.com/usenbai-nur/ADP2_asik2_protos.git proto-src

      - name: Generate Go files
        run: |
          cd proto-src
          protoc \
            --proto_path=. \
            --go_out=../ \
            --go_opt=paths=source_relative \
            --go-grpc_out=../ \
            --go-grpc_opt=paths=source_relative \
            order/v1/order.proto \
            payment/v1/payment.proto

      - name: Remove cloned proto repo
        run: |
          rm -rf proto-src

      - name: Show generated files
        run: |
          find order payment -type f

      - name: Commit and push generated files
        run: |
          git config user.name "usenbai-nur"
          git config user.email "usenbai.nur@users.noreply.github.com"
          git add .
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "generate protobuf files"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/usenbai-nur/ADP2_asik2_generated.git HEAD:main
